global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']
    metrics_path: '/metrics'

  - job_name: 'defects-service'
    static_configs:
      - targets: ['defects-service:8000']
    metrics_path: '/metrics'
