
    
from uuid import uuid4

from infrastructure.services.token import JSONWebTokenService
from domain.services.token import BaseTokenService


if __name__ == "__main__":
    jwt_service: BaseTokenService = JSONWebTokenService()
    print(jwt_service.verify_access_token(
        "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NGY2NGNhMS04ZTJlLTQ2YWEtYjk4Yy03NTI4NjFiMWFlZDgiLCJqdGkiOiI3MzQ0N2FiZC1iMDI4LTQ2YmMtYjZlYy1mZGE5MGFjNTIzZjkiLCJ0eXBlIjoiYWNjZXNzIiwiZnJlc2giOmZhbHNlLCJjc3JmIjoiIiwiaWF0IjoxNzc1NTkzMjk1LCJleHAiOjE3NzU1OTUwOTUuMTIyNzc2LCJ1c2VyX29pZCI6ImY3ZDQ0ZTExLTU0ZjgtNDJlNS04OGQ1LTA3ODIwNDVjOTM3MyIsInRva2VuX29pZCI6IjlkOTE4ZjI5LWQ5ODUtNDY5Ny1hYzI1LWE3ZDViZjNkNjU3NSIsImlzX3ZlcmlmaWVkIjp0cnVlLCJzY29wZXMiOlsicGVybWlzc2lvbnMuZGVsZXRlIiwidXNlcnMuZGVhY3RpdmF0ZSIsInVzZXJzLmxvZ291dCIsInJvbGVzLmdldCIsInJvbGVzLmNyZWF0ZSIsInVzZXJzLmFjdGl2YXRlIiwidXNlcnMucmV2b2tlLXJvbGUiLCJyb2xlcy5kZWxldGUiLCJyb2xlcy5yZXZva2UtcGVybWlzc2lvbiIsInBlcm1pc3Npb25zLmNyZWF0ZSIsInJvbGVzLnVwZGF0ZSIsInBlcm1pc3Npb25zLnVwZGF0ZSIsInVzZXJzLmdldCIsInVzZXJzLmdldC1tZSIsInJvbGVzLmFzc2lnbi1wZXJtaXNzaW9uIiwicGVybWlzc2lvbnMuZ2V0IiwidXNlcnMudmVyaWZ5IiwidXNlcnMuYXNzaWduLXJvbGUiXX0.VjhxlMm7jw82QthqN78Sh6GMFNhXJWLuVMoiC0T04sMOrS0OfD4adXcwv8wkT4_U1k7KRBJFzGUu9xd8Vinw2yvcqtM-LMh8schUps9f7zQB1fD5iT2VkNCUwaSzftjhbj3pkjNkTDNrRp18gkZNZEVIN6fF9sFiXJeDywlj_eu3_JrlwStPd-z4usQs-HWfMbBed7n91CC-Z2Ey5mdRs7gW9OZNcLZSzfOw8-NqETzfQzsxzM3UI_-KDNGPhTVyKcME6gPi50cK_pMkvZSlEo-p_ksAcIvfSuf5HlDU5qo78rSe8jMVgiDXqwHed-PsxGlBrYi_vCeSSBGb4aiCiQ"
    ))
    