server {
    listen 8080;
    server_name localhost;

    location /stub_status {
        stub_status;
        access_log off;
        allow 127.0.0.1;
        allow 172.0.0.0/8;
        deny all;
    }
}

server {
    listen 80;
    server_name localhost;

    # ==================== METRICS ====================
    
    location /metrics {
        proxy_pass http://auth-service:8000/metrics;
        proxy_set_header Host $host;
    }

    # ==================== AUTH SERVICE ====================
    # Все запросы к /auth-service/ перенаправляются в auth-service
    
    location /auth-service/ {
        # Убираем /auth-service из пути при проксировании
        rewrite ^/auth-service/(.*)$ /$1 break;
        proxy_pass http://auth-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # ==================== DEFECTS SERVICE ====================
    # Все запросы к /defects-service/ перенаправляются в defects-service
    
    location /defects-service/ {
        # Убираем /defects-service из пути при проксировании
        rewrite ^/defects-service/(.*)$ /$1 break;
        proxy_pass http://defects-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # ==================== HEALTH ====================

    location /health {
        access_log off;
        return 200 "OK\n";
        add_header Content-Type text/plain;
    }
}