"""update

Revision ID: 7beafd9d7ad3
Revises: 
Create Date: 2026-03-28 11:08:39.719729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7beafd9d7ad3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('login_history',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('user_oid', sa.String(), nullable=False),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_oid'], ['users.oid'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_login_history_user_oid'), 'login_history', ['user_oid'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_oid', sa.String(), nullable=False),
    sa.Column('permission_oid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['permission_oid'], ['permissions.oid'], ),
    sa.ForeignKeyConstraint(['role_oid'], ['roles.oid'], ),
    sa.PrimaryKeyConstraint('role_oid', 'permission_oid')
    )
    op.create_table('user_roles',
    sa.Column('user_oid', sa.String(), nullable=False),
    sa.Column('role_oid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_oid'], ['roles.oid'], ),
    sa.ForeignKeyConstraint(['user_oid'], ['users.oid'], ),
    sa.PrimaryKeyConstraint('user_oid', 'role_oid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_login_history_user_oid'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
